### ISSUE TITLE
服务器MOTD显示错误

### ISSUE THREAD

**Issue by 3zeroed** [wode490390/Nukkit#24]
### Expected Behavior

服务器MOTD正常显示

### Actual Behavior

显示lifeboat的服务器MOTD

### Steps to Reproduce

这是个几率性的BUG，有时会出现，有时不会

### Debug information

* Debug link:NULL
* Timings link (if relevant):NULL

### Crashdump, Backtrace or Other Files

此BUG无Crashdump, Backtrace或其他文件可提供
只有一张图片：![图片](https://raw.githubusercontent.com/Anders233/Nukkit/master/2019-04-29-13-12-13-101_com.mojang.min.png)
**Checklist**:

- [x] I included a `/debugpaste` link
- [x] I made sure there aren't duplicates of this report [(Use Search)](https://github.com/NukkitX/Nukkit/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of Nukkit
- [x] I Made sure the bug/error is not caused by a plugin

**Comment by Anders233** [comment]
起先觉得的动态MOTD插件引起的问题，后来卸载之后仍会出现此特性，所以我觉得，应该不是动态MOTD显示的锅。

**Comment by wode490390** [comment]
Fixed in https://github.com/NukkitX/Nemisys/pull/43
