### ISSUE TITLE
铁砧修复问题

### ISSUE THREAD

**Issue by BeerMC** [wode490390/Nukkit#43]
铁砧的操作过程：
放置有损耗的钻石剑，钻石x64-->点击第三个结果槽位--->第一格钻石剑被消耗，第二格钻石数减一，第三格修复后的钻石剑无法取下。
若修复时钻石数改为1，则修复正常

**Comment by wode490390** [comment]
Duplicate of https://github.com/NukkitX/Nukkit/issues/831
